### ISSUE TITLE
Build failure with GHC 7.8

### ISSUE THREAD

**Issue by snoyberg** [Daniel-Diaz/binary-list#2]
I was wondering who would win the award for first "only builds on 7.10" :)

```
[1 of 3] Compiling Data.BinaryList.Internal ( Data/BinaryList/Internal.hs, dist/build/Data/BinaryList/Internal.o )
[2 of 3] Compiling Data.BinaryList  ( Data/BinaryList.hs, dist/build/Data/BinaryList.o )

Data/BinaryList.hs:534:10:
    Not in scope: type constructor or class ‘Foldable’

Data/BinaryList.hs:546:10:
    Not in scope: type constructor or class ‘Traversable’
cabal: Error: some packages failed to install:
binary-list-1.1.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by Daniel-Diaz** [comment]
Yeah, I wrote a warning in the package description about this. It will be fixed later today.

Thanks.

**Comment by Daniel-Diaz** [comment]
As promised, version 1.1.0.1 of binary-list is released and compatible with previous versions of GHC. Feel free to re-open if that is not the case.
